### ISSUE TITLE
How to get 80sps

### ISSUE THREAD

**Issue by hochers** [gandalf15/HX711#11]
Hi, 
i soldered the rate pin to 3.3v but the rate i can get values in a loop stays the same. How do i get up to 80sps? (I am using a rpi zero)

Thank you

**Comment by hochers** [comment]
I did it, but it didn't change anything

**Comment by gandalf15** [comment]
If you measure voltage with multimeter, what is the voltage on the pin? Can you send a picture? If you try continuity with multimeter do you have it to VCC do you have it to Ground?
How often are you trying to read the HX711 with your code? Can you send a snippet of your code?
Thanks.
