### ISSUE TITLE
Do I need to calibrate each time ?

### ISSUE THREAD

**Issue by adriencarbonaro** [gandalf15/HX711#13]
This is more a question than an issue.
Do I need to calibrate each time I'm using it ? I would like to use my program on a cron tab to get a weight and send it to my database. But I can't calibrate with a known weight each time (the purpose would be to use it at night for example).

Thank you !

**Comment by gandalf15** [comment]
Hi! Of course you don't have to. Check out this exampel: https://github.com/gandalf15/HX711/blob/master/HX711_Python3/example_save_state.py

**Comment by gandalf15** [comment]
Once you set the ratio and offset save the object and reuse it again whenever you want.

**Comment by adriencarbonaro** [comment]
Oh I didn't see your latest changes. Thank you ! :)
