### ISSUE TITLE
GPIO.setmode(GPIO

### ISSUE THREAD

**Issue by adriencarbonaro** [gandalf15/HX711#14]
I commented a line on one of your previous commits (#5e5d9). I think this line is needed. What do you think ?

https://github.com/gandalf15/HX711/commit/5e5d9667717892728cdfa13701f9a3c822393383#r31858297

**Comment by gandalf15** [comment]
No. You have to set the mode in the file that uses the HX711 class. The reason for this is that the class should be independant of the GPIO mode you are going to use.

**Comment by gandalf15** [comment]
Does it make sense? I am opened for the discussion. Thanks

**Comment by adriencarbonaro** [comment]
You're actually right and you set it in the first line of your example so that is a good workflow ! Thank you !
