### ISSUE TITLE
Can you guide, which pins to connect with which GNIO on Raspberry Pi 3B+ ?

### ISSUE THREAD

**Issue by memuhhib** [gandalf15/HX711#29]
Hi, Thanks for this great source. We are doing a school project with this, I want you to kindly let us know which pins you have put with corresponding pins of Raspberyy Pi 3B+ or which shall we for this code :))
Thanks, Have a nice day :)

**Comment by gandalf15** [comment]
Hi there,
I am sorry for the very late reply but I've been busy. If you look at the file : https://github.com/gandalf15/HX711/blob/master/HX711_Python3/example.py 
and read through you will see that there are comments that describes how to use this code. Look at the line 9. I used pins 21 and 20 but you can use any pin you want and the specify it in the code. I hope this helps.
