### ISSUE TITLE
Will it work on NVIDIA Jetson Nano?

### ISSUE THREAD

**Issue by bharat8** [gandalf15/HX711#32]
Hey @gandalf15, I have implemented your library on Raspberry Pi 4 and it works really good. But i have a doubt of it working on a NVIDIA Jetson Nano as i have tried it recently and it only shows the error of **no median for empty data**. 

Is there any method to make it work on this board?

**Comment by gandalf15** [comment]
Hi there,
I am sorry for the very late reply but I've been busy. Unfortunately, it does not work on this board. You may be able to modify it but I think that could be a lot of work.

**Comment by crq-13** [comment]
Hey @gandalf15 can you tell me why it does not work on the jetson nano?
