### ISSUE TITLE
Crashing after 10s

### ISSUE THREAD

**Issue by JeanSolagnier** [gandalf15/HX711#39]
Dear Gandalf,

I have a problem that the example.py will crash after about 10 seconds. I think it is not reading enough samples and the datalist
 runs out of numbers and cant calculate the median anymore.

I am using a Raspberry pi Zero. HX711 has been modified to 80SPS.
I am using GPIO 5 as Dout and GPIO 6 as SCK.  I also have to write 5 and 6 in the example.py instead of 29 and 31 as per BCM numbering, which I find strange. Can you explain this also?
I really want to use your code since it has the most stable readings compared to others.

Can you help me out?

![20201223_013248](https://user-images.githubusercontent.com/67872569/102947773-6133de00-44c4-11eb-92ba-7bd1dbc33f43.jpg)

**Comment by JeanSolagnier** [comment]
I have tried hx._read() in a while loop to see the results and a lot of them come back as "false".
![20201223_200515](https://user-images.githubusercontent.com/67872569/103030002-334da880-455b-11eb-96a4-2e016d452ea6.jpg)

**Comment by MilkCrate745** [comment]
I'm also having the same issue. When i try running the example.py it just crashes after a few seconds with the same error message.

I ran the loop you wrote and there are a lot of false readings. It seems cyclical, there are a few good readings and then a ton of false readings, repeat.

**Comment by gandalf15** [comment]
Try now with the latest commit. It should solve the problem.
