### ISSUE TITLE
"module '8' has no attribute 'select_channel'"

### ISSUE THREAD

**Issue by Pudding01** [gandalf15/HX711#9]
So I'm trying to make a quick code that just prints out what the chip is reading and it's giving me weird errors. My current code (relevant parts anyway) are as follows:
import hx711 as HX

HX.__init__('8', '10')
sleep(1)
print('test')
HX.select_channel('A')
print(HX.zero())
while(true):
if(HX._ready()):
print(HX._read())

and it's currently giving me:
"test
Traceback...
...
HX.select_channel('A')
AttributeError: module '8' has no attribute 'select_channel'
"

And I have no idea why it's not using HX but instead this mysterious '8' (I'm guessing it's getting 8 from the init(8,10) bit)

Any idea if it's my code or not?

Edit: Using the Python3 version, a zeroW with Python3 on it

Edit 2: Should really have looked at the example before trying to get it to work myself.

Got it working

**Comment by gandalf15** [comment]
You figured it out. in HX.init you used string instead of int type. However it is interesting why it did not catch this during initialisation. There is type checkin ... I'll have to look at it. BTW am I right with the string '8'? Once you used int type this error disappeared?
